name: Provision t2.micro EC2

on:
  push:
    
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY}}
          aws-region: us-east-2
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      
      - name: Terraform Apply
        id:   apply
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve

      - name: List directory contents for debugging
        run: |
          ls -R
          ls -R DevOps-training-Project
          ls -R DevOps-training-Project/Ansible 
          
      - name: Run playbooks
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: Playbooks.yml
          directory: ./DevOps-training-Project/Ansible/Playbooks.yml

          key: ${{secrets.MY_SECRET_KEYPAIR}}
          inventory: |
            [all]
            44.210.104.196

            env:
          ANSIBLE_STDOUT_CALLBACK: debug
          
            # Optional, SSH known hosts file content
           # known_hosts: |
            # example.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl